### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Return value of Phpactor\Indexer\Model\Record\ClassRecord or null, instance of __PHP_Incomplete_Class returned 

### ISSUE THREAD

**Issue by gvanbeck** [phpactor/language-server-extension#4]
server is running but crashes

`[2020-04-06 08:28:28] phpactor.INFO: REQUEST {"jsonrpc":"2.0","method":"initialized","params":[]} []
[2020-04-06 08:28:28] phpactor.INFO: Starting service: Phpactor\Indexer\Extension\LanguageServer\IndexerHandler::indexerService [] []
[2020-04-06 08:28:29] phpactor.INFO: RESPONSE {"method":"window/showMessage","params":{"type":3,"message":"Indexing \"3650\" PHP files"},"jsonrpc":"2.0"} []
PHP Fatal error:  Uncaught TypeError: Return value of Phpactor\Indexer\Adapter\Php\Serialized\FileRepository::getClass() must be an instance of Phpactor\Indexer\Model\Record\ClassRecord or null, instance of __PHP_Incomplete_Class returned in ~/.config/nvim/plugged/phpactor/vendor/phpactor/indexer/lib/Adapter/Php/Serialized/FileRepository.php:52
Stack trace:
#0 ~/.config/nvim/plugged/phpactor/vendor/phpactor/indexer/lib/Adapter/Php/Serialized/SerializedQuery.php(39): Phpactor\Indexer\Adapter\Php\Serialized\FileRepository->getClass(Object(Phpactor\Name\FullyQualifiedName))
#1 ~/.config/nvim/plugged/phpactor/vendor/phpactor/indexer/lib/Adapter/Worse/WorseIndexBuilder.php(133): Phpactor\Indexer\Adapter\Php\Serialized\SerializedQuery->class(Object(Phpactor\Name\FullyQualifiedName))
#2 ~/.config/nvim/plugged/phpactor/vendor/phpactor/indexer/lib/Adapter/Worse/WorseIndexBuilder.php(114): Phpactor\Indexer\Adapter\Worse\WorseIndexBuilder->createO in ~/.config/nvim/plugged/phpactor/vendor/phpactor/indexer/lib/Adapter/Php/Serialized/FileRepository.php on line 52`

**Comment by dantleech** [comment]
Interesting -- could you try removing the cache?

```
rm -Rf ~/.cache/phpactor/index
```

Could it be that you ran the indexer initially some time ago?

In anycase would be good to handle this type of issue.

**Comment by gvanbeck** [comment]
Yup did that indeed. Removing the cache did it. Thx.

**Comment by dantleech** [comment]
Created https://github.com/phpactor/language-server-extension/issues/4
